apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  namespace: sisclinica 
  name: app-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app
