apiVersion: v1
data:
  .editorconfig: |
    root = true

    [*]
    charset = utf-8
    end_of_line = lf
    indent_size = 4
    indent_style = space
    insert_final_newline = true
    trim_trailing_whitespace = true

    [*.md]
    trim_trailing_whitespace = false

    [*.{yml,yaml}]
    indent_size = 2

    [docker-compose.yml]
    indent_size = 4
  .env: |
    APP_NAME=laravel
    APP_ENV=local
    APP_KEY=
    APP_DEBUG=true
    APP_URL=http://localhost:8080

    APP_LOCALE=en
    APP_FALLBACK_LOCALE=en
    APP_FAKER_LOCALE=en_US

    APP_MAINTENANCE_DRIVER=file
    APP_MAINTENANCE_STORE=database

    BCRYPT_ROUNDS=12

    LOG_CHANNEL=stack
    LOG_STACK=single
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug

    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=user
    DB_PASSWORD=password

    SESSION_DRIVER=database
    SESSION_LIFETIME=120
    SESSION_ENCRYPT=false
    SESSION_PATH=/
    SESSION_DOMAIN=null

    BROADCAST_CONNECTION=log
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=database

    CACHE_STORE=database
    CACHE_PREFIX=

    MEMCACHED_HOST=localhost

    REDIS_CLIENT=phpredis
    REDIS_HOST=localhost
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_MAILER=log
    MAIL_HOST=localhost
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS="hello@example.com"
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=
    AWS_USE_PATH_STYLE_ENDPOINT=false

    VITE_APP_NAME="${APP_NAME}"
  .gitattributes: |
    * text=auto eol=lf

    *.blade.php diff=html
    *.css diff=css
    *.html diff=html
    *.md diff=markdown
    *.php diff=php

    /.github export-ignore
    CHANGELOG.md export-ignore
    .styleci.yml export-ignore
  artisan: |
    #!/usr/bin/env php
    <?php

    use Symfony\Component\Console\Input\ArgvInput;

    define('LARAVEL_START', microtime(true));

    // Register the Composer autoloader...
    require __DIR__.'/vendor/autoload.php';

    // Bootstrap Laravel and handle the command...
    $status = (require_once __DIR__.'/bootstrap/app.php')
        ->handleCommand(new ArgvInput);

    exit($status);
  phpunit.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
             bootstrap="vendor/autoload.php"
             colors="true"
    >
        <testsuites>
            <testsuite name="Unit">
                <directory>tests/Unit</directory>
            </testsuite>
            <testsuite name="Feature">
                <directory>tests/Feature</directory>
            </testsuite>
        </testsuites>
        <source>
            <include>
                <directory>app</directory>
            </include>
        </source>
        <php>
            <env name="APP_ENV" value="testing"/>
            <env name="APP_MAINTENANCE_DRIVER" value="file"/>
            <env name="BCRYPT_ROUNDS" value="4"/>
            <env name="CACHE_STORE" value="array"/>
            <!-- <env name="DB_CONNECTION" value="sqlite"/> -->
            <!-- <env name="DB_DATABASE" value=":memory:"/> -->
            <env name="MAIL_MAILER" value="array"/>
            <env name="PULSE_ENABLED" value="false"/>
            <env name="QUEUE_CONNECTION" value="sync"/>
            <env name="SESSION_DRIVER" value="array"/>
            <env name="TELESCOPE_ENABLED" value="false"/>
        </php>
    </phpunit>
  postcss.config.js: |
    export default {
      plugins: {
        tailwindcss: {},
        autoprefixer: {},
      },
    }
  tailwind.config.js: |+
    /** @type {import('tailwindcss').Config} */
    export default {
      content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
      ],
      theme: {
        extend: {},
      },
      plugins: [],
    }

  vite.config.js: "import { defineConfig } from 'vite';\nimport laravel from 'laravel-vite-plugin';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({\n    server: { \n        hmr: {\n            host: '127.0.0.1',\n        },\n    }, \n    plugins: [\n        laravel({\n            input: [\n                'resources/css/app.css',\n                'resources/js/app.js',\n            ],\n            refresh: true,\n        }),\n        vue({\n            template: {\n                transformAssetUrls: {\n                    base: null,\n                    includeAbsolute: false,\n                },\n            },\n        }),\n    ],\n    resolve: {\n        alias: {\n            vue: 'vue/dist/vue.esm-bundler.js',\n        },\n    },\n});\n"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: app
  name: app-cm0
