apiVersion: apps/v1
kind: Deployment
metadata:
  name: "laravel"
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      run: laravel
  template:
    metadata:
      labels:
        run: laravel
    spec:
      containers:
#================================================================
      - name: "laravel-app"
        image: "lkaetsu/laravel-app"
        volumeMounts: 
        - name: app-volume
          mountPath: /var/www
#================================================================
      - name: "mysql"
        image: "mysql:8.3.0"
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${DB_PASSWORD}
#================================================================
      - name: "phpmyadmin"
        image: "phpmyadmin/phpmyadmin"
        ports:
          - containerPort: 8081
#================================================================
      - name: "nginx"
        image: "nginx:alpine"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-volume
          mountPath: /var/www
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
#================================================================
      - name: "laravel-node"
        image: "lkaetsu/laravel-node"
        ports:
          - containerPort: 5173
        env: 
          - name: APP_KEY
            value: ${APP_KEY}
#================================================================
      volumes:
      - name: app-volume
        hostPath:
          path: /var/www
      - name: nginx-conf
        hostPath: 
          path: /var/www/.docker/nginx.conf
      - name: laravel-node
        hostPath:
          path: /var/www/node_modules
      - name: mysql-persistent-storage
        hostPath:
          path: /var/www/.docker/mysql