apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  namespace: sisclinica
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.3.0
          name: mysql
          envFrom:
            - configMapRef:
                name: mysql-cm0
          ports:
          - name: mysql
            containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-claim0
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
        - configMap:
            name: mysql-cm0
          name: mysql-cm0