apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mysql"
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: "mysql"
        image: "mysql:8.3.0"
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${DB_PASSWORD}
      - name: "phpmyadmin"
        image: "phpmyadmin/phpmyadmin"
        ports:
          - containerPort: 8081
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /var/www/.docker/mysql