apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-claim0
  namespace: sisclinica
  name: mysql-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
