apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/sistema-de-clinica-mynetwork: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - image: mysql:8.3.0
          name: mysql
          envFrom:
            - configMapRef:
                name: mysql-cm0
          ports:
          - name: mysql
            containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
        - configMap:
            name: mysql-cm0
          name: mysql-cm0