apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx"
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:      
      - name: "nginx"
        image: "nginx:alpine"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-volume
          mountPath: /var/www
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: app-volume
        hostPath:
          path: /var/www
      - name: nginx-conf
        hostPath: 
          path: /var/www/.docker/nginx.conf