apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  namespace: sisclinica
  name: node
spec:
  type: NodePort
  ports:
    - name: node
      port: 5173
      protocol: TCP
  selector:
    app: node