apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/sistema-de-clinica-mynetwork: "true"
        io.kompose.service: node
    spec:
      containers:
        - image: lkaetsu/laravel-node
          name: laravel-node
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www
              name: node-cm0
            - mountPath: /var/www/node_modules
              name: node-claim1
          workingDir: /var/www
      restartPolicy: Always
      volumes:
        - configMap:
            name: node-cm0
          name: node-cm0
        - name: node-claim1
          persistentVolumeClaim:
            claimName: node-claim1
