apiVersion: apps/v1
kind: Deployment
metadata:
  name: "node"
  labels:
    app: node
spec:
  selector:
    matchLabels:
      run: node
  template:
    metadata:
      labels:
        run: node
    spec:
      containers:
      - name: "laravel-node"
        image: "lkaetsu/laravel-node"
        ports:
          - containerPort: 5173
        env: 
          - name: APP_KEY
            value: ${APP_KEY}
      volumes:
      - name: laravel-node
        hostPath:
          path: /var/www/node_modules