apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  namespace: sisclinica
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always