apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  namespace: sisclinica
  name: phpmyadmin
spec:
  type: NodePort
  ports:
    - name: phpmyadmin
      port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    app: phpmyadmin