apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort 
  selector:
    run: phpmyadmin
  ports:
    - port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "phpmyadmin"
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      run: phpmyadmin
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      containers:
      - name: "phpmyadmin"
        image: "phpmyadmin/phpmyadmin"
        ports:
          - containerPort: 8081